import os
import json
import re

MATRIX_PATH = os.path.join(
    os.path.dirname(__file__), "strategies_index_vector_matrix.json"
)
VAULT_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "../../obsidian_vault/strategies")
)


def clean_filename(name):
    clean = re.sub(r"[^a-zA-Z0-9\s]", "", name)
    return clean.strip().replace(" ", "_").lower()


def main():
    if not os.path.exists(VAULT_DIR):
        os.makedirs(VAULT_DIR)

    with open(MATRIX_PATH, "r") as f:
        data = json.load(f)

    metadata = data.get("metadata", [])

    index_links = []

    for entry in metadata:
        # Strategy: Covered call
        if "Strategy:" in entry:
            parts = entry.split("Strategy:")
            chapter_info = parts[0].strip()
            rest = parts[1]

            # Remove the trailing dots and page number using a loose match for dots
            clean_rest = re.sub(r"\s*(?:\.\s*)*\d*$", "", rest).strip()
            if not clean_rest:
                clean_rest = "Unknown Strategy"

            # Extract page number if present
            page_match = re.search(r"\s+(\d+)$", entry)
            page_num = page_match.group(1) if page_match else "Unknown"

            filename = f"{clean_filename(clean_rest)}.md"
            filepath = os.path.join(VAULT_DIR, filename)

            content = f"""# {clean_rest}

**Chapter Index:** {chapter_info}
**Source Page:** {page_num}

## Summary
*(To be generated by Wiki Architect)*

## Code Implementation Draft
*(To be generated by Wiki Architect)*

## Known Exploits or Variants
*(To be generated by Wiki Architect)*
"""
            with open(filepath, "w") as out_f:
                out_f.write(content)

            index_links.append(
                f"- [[{clean_filename(clean_rest)}]] : {clean_rest} (Pg {page_num})"
            )

    # Write the master index file
    index_path = os.path.join(VAULT_DIR, "_master_index.md")
    with open(index_path, "w") as f:
        f.write("# Master Quantitative Strategies Wiki\n\n")
        f.write("\n".join(index_links))

    print(
        f"Successfully exploded {len(index_links)} strategy JSON nodes into Obsidian Markdown pages at {VAULT_DIR}."
    )


if __name__ == "__main__":
    main()
