import pandas as pd
import numpy as np

# This script is the Inner Loop for the Bilevel Architecture.
# The Bilevel Meta-Agent actively overwrites the `calculate_alpha` block.
# DO NOT RENAME THE FUNCTION `calculate_alpha`

def calculate_alpha(prices: pd.Series) -> pd.Series:
    """
    Returns a pandas Series of signals: 1 for LONG, -1 for SHORT, 0 for NEUTRAL.
    """
    signal = pd.Series(0, index=prices.index)
    # [META-INJECTION START]
    # AUTOGENERATED BY META-AGENT ITERATION 5
import pandas as pd

    delta = prices.diff()
    gain = delta.clip(lower=0).rolling(14).mean()
    loss = (-delta.clip(upper=0)).rolling(14).mean()
    rsi = 100.0 - (100.0 / (1.0 + gain / (loss + 1e-8)))

    mom = prices.pct_change(20)
    mom_z = (mom - mom.rolling(60).mean()) / (mom.rolling(60).std() + 1e-8)

    vol = prices.pct_change().rolling(10).std()
    vol_z = (vol - vol.rolling(60).mean()) / (vol.rolling(60).std() + 1e-8)

    sma_50 = prices.rolling(50).mean()

    signal = pd.Series(0, index=prices.index, dtype=int)
    signal.loc[(rsi < 40) & (mom_z > -1.0) & (prices > sma_50) & (vol_z < 1.5)] = 1
    signal.loc[(rsi > 60) & (mom_z < 1.0) & (prices < sma_50) & (vol_z < 1.5)] = -1
    # [META-INJECTION END]
    return signal

def run_backtest():
    # Deterministic price generation to allow fair relative comparison across thousands of iterations
    np.random.seed(42)
    daily_drift = 0.0002
    daily_vol = 0.015
    market_returns = np.random.normal(daily_drift, daily_vol, 2000)
    prices = pd.Series(100 * np.exp(np.cumsum(market_returns)))
    
    signals = calculate_alpha(prices)
    
    # Execution shifted by 1 to prevent data leakage (cannot trade on same-day close knowing it in advance)
    strategy_returns = signals.shift(1).fillna(0) * market_returns
    
    cumulative_returns = np.exp(np.cumsum(strategy_returns)) - 1
    cagr = (cumulative_returns.iloc[-1] + 1) ** (252 / 2000) - 1
    
    sharpe_ratio = 0.0
    if strategy_returns.std() != 0:
        sharpe_ratio = (strategy_returns.mean() / strategy_returns.std()) * np.sqrt(252)
        
    print(f"CUMULATIVE_RETURN: {cumulative_returns.iloc[-1]:.4f}")
    print(f"CAGR: {cagr:.4f}")
    print(f"SHARPE_RATIO: {sharpe_ratio:.4f}")

if __name__ == "__main__":
    run_backtest()
